language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_script:
    - sudo apt-get install pandoc
    - git clone --depth=50 git://github.com/ovgu-ttz/pyandoc.git chaimleib/pyandoc
    - ln -s chaimleib/pyandoc/pandoc chaimleib/intervaltree/pandoc
script:
    - python setup.py develop test
