language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - make deps-dev
    - pip install coverage==3.7.1
script:
    coverage run --source=intervaltree setup.py develop test
after_success:
    coverage report
