language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - make deps-dev
    - pip install coveralls
script:
    coverage run --source=intervaltree setup.py develop test
after_success:
    coveralls

