language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - make deps-dev
    - pip install coverage
script:
    coverage run --source=intervaltree setup.py develop test
after_success:
    coverage report
